# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v8.3.9
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod: {}
domains_test: {}
gitlab_url: ""
odoo_dbfilter: ^prod
odoo_initial_lang: en_US
odoo_listdb: false
odoo_oci_image: ""
odoo_proxy: traefik
odoo_version: 18.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: "16"
project_author: PT. Simetri Sinergi Indonesia
project_license: BSL-1.0
project_name: odoo18-dev
smtp_default_from: ""
smtp_relay_host: ""
traefik_version: 2
